### ISSUE TITLE
Crash with Latest Phosphor for 1.12.2. 

### ISSUE THREAD

**Issue by furtabs** [jaredlll08/DarkRooms#1]
The one that was released earlier still works but the latest doesn't

https://pastebin.com/Tbj7jDuQ

**Comment by jaredlll08** [comment]
I'm fairly sure this isn't caused by my mod and that there is a bigger issue with your install (all those mixin calls shouldn't be attributed to me).

Regardless, 1.12 is no longer supported, sorry.
